require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/schema.rb'
  NewCops: enable

Layout/LineLength:
  Max: 150

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Rails/EnvironmentVariableAccess:
  AllowReads: true

Rails/FilePath:
  Enabled: false

Rails/Present:
  Exclude:
    - 'bin/bundle'

Rails/Presence:
  Enabled: false

Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

RSpec/DescribedClass:
  EnforcedStyle: explicit

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

RSpec/FactoryBot/SyntaxMethods:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashSyntax:
  Enabled: false

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: new_line

Style/SlicingWithRange:
  Enabled: true

### To be fixed

Lint/MissingSuper:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/FilePath:
  Exclude:
    - spec/scopes/*

RSpec/NamedSubject:
  Enabled: false

Style/OptionalBooleanParameter:
  Exclude:
    - 'app/workers/**/*'
