default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["POSTGRES_HOST"] %>
  database: <%= ENV["POSTGRES_DATABASE"] %>
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: store_app_development

test:
  <<: *default
  database: store_app_test

production:
  <<: *default
  database: store_app_production
  username: store_app
  password: <%= ENV["STORE_APP_DATABASE_PASSWORD"] %>
